// Genres facon iTunes / Apple Music, enrichis pour le repertoire de XOL
// (afro, afro-latin, gospel...). Utilises dans les listes deroulantes.
export const GENRES: string[] = [
  "Afrobeats",
  "Afro-Latin",
  "Afro House",
  "Afro Pop",
  "Alternative",
  "Blues",
  "Classical",
  "Country",
  "Dance",
  "Electronic",
  "Folk",
  "Funk",
  "Gospel",
  "Hip-Hop/Rap",
  "House",
  "Instrumental",
  "Jazz",
  "Latin",
  "Metal",
  "Pop",
  "Punk",
  "R&B/Soul",
  "Reggae",
  "Rock",
  "Singer/Songwriter",
  "Soul",
  "Soundtrack",
  "Spoken Word",
  "Vocal",
  "World",
];
